name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: CMake config
      run: |
        mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        cmake ..
    - name: CMake build
      run: |
        cd ${{ github.workspace }}/build
        cmake --build .
